//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vueAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_module
    {
        public base_module()
        {
            this.base_moduleForm = new HashSet<base_moduleForm>();
        }
    
        public int isid { get; set; }
        public string rowID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
        public string componentPath { get; set; }
        public string componentName { get; set; }
        public Nullable<int> sort { get; set; }
        public string description_tw { get; set; }
        public string description_en { get; set; }
        public string description_other { get; set; }
    
        public virtual ICollection<base_moduleForm> base_moduleForm { get; set; }
    }
}
