//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vueAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_token
    {
        public int isid { get; set; }
        public string userID { get; set; }
        public string token { get; set; }
        public string secretKey { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<int> status { get; set; }
        public string Client { get; set; }
        public long secretID { get; set; }
    }
}
