//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vueAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_moduleFormAuthorize
    {
        public base_moduleFormAuthorize()
        {
            this.base_moduleFormAuthorizeAction = new HashSet<base_moduleFormAuthorizeAction>();
        }
    
        public int isid { get; set; }
        public string rowID { get; set; }
        public string formID { get; set; }
        public string authorizeName { get; set; }
        public Nullable<int> authorizeValue { get; set; }
    
        public virtual base_moduleForm base_moduleForm { get; set; }
        public virtual ICollection<base_moduleFormAuthorizeAction> base_moduleFormAuthorizeAction { get; set; }
    }
}
