//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vueAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_company
    {
        public base_company()
        {
            this.base_dept = new HashSet<base_dept>();
            this.base_position = new HashSet<base_position>();
        }
    
        public int isid { get; set; }
        public string rowID { get; set; }
        public string companyCode { get; set; }
        public string companyName_chs { get; set; }
        public string companyName_en { get; set; }
        public string parentID { get; set; }
        public string parentFullID { get; set; }
        public string parentFullName { get; set; }
        public string principalName { get; set; }
        public string principalPhone { get; set; }
        public string principalEmail { get; set; }
        public string address { get; set; }
        public int levelID { get; set; }
    
        public virtual ICollection<base_dept> base_dept { get; set; }
        public virtual ICollection<base_position> base_position { get; set; }
    }
}
