//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vueAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_userRelation
    {
        public int isid { get; set; }
        public string rowID { get; set; }
        public string userID { get; set; }
        public Nullable<int> Category { get; set; }
        public string ObjectID { get; set; }
        public string createUser { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    
        public virtual base_user base_user { get; set; }
    }
}
