//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vueAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_user
    {
        public base_user()
        {
            this.base_userRelation = new HashSet<base_userRelation>();
        }
    
        public int isid { get; set; }
        public string rowID { get; set; }
        public string account { get; set; }
        public string userName { get; set; }
        public string sex { get; set; }
        public string companyID { get; set; }
        public string deptID { get; set; }
        public string phone { get; set; }
        public int status { get; set; }
        public string remark { get; set; }
        public string createUser { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string password { get; set; }
        public string updateUser { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    
        public virtual ICollection<base_userRelation> base_userRelation { get; set; }
    }
}
