//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vueAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_Authorize
    {
        public int isid { get; set; }
        public string rowID { get; set; }
        public Nullable<int> category { get; set; }
        public string objectID { get; set; }
        public Nullable<int> itemType { get; set; }
        public string itemID { get; set; }
        public Nullable<int> sort { get; set; }
        public string createUser { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
