//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vueAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_APIList
    {
        public base_APIList()
        {
            this.base_moduleFormAuthorizeAction = new HashSet<base_moduleFormAuthorizeAction>();
            this.base_moduleFormActions = new HashSet<base_moduleFormActions>();
        }
    
        public int isid { get; set; }
        public string rowID { get; set; }
        public string APIName { get; set; }
        public string url { get; set; }
        public int checkType { get; set; }
        public string createUser { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    
        public virtual ICollection<base_moduleFormAuthorizeAction> base_moduleFormAuthorizeAction { get; set; }
        public virtual ICollection<base_moduleFormActions> base_moduleFormActions { get; set; }
    }
}
