//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vueAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_moduleForm
    {
        public base_moduleForm()
        {
            this.base_moduleFormAuthorize = new HashSet<base_moduleFormAuthorize>();
            this.base_moduleFormAuthorizeAction = new HashSet<base_moduleFormAuthorizeAction>();
            this.base_moduleFormActions = new HashSet<base_moduleFormActions>();
        }
    
        public int isid { get; set; }
        public string rowID { get; set; }
        public string mainID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string routeName { get; set; }
        public string componentPath { get; set; }
        public string componentName { get; set; }
        public Nullable<int> sort { get; set; }
        public string icon { get; set; }
        public string description_tw { get; set; }
        public string description_en { get; set; }
        public string description_other { get; set; }
    
        public virtual base_module base_module { get; set; }
        public virtual ICollection<base_moduleFormAuthorize> base_moduleFormAuthorize { get; set; }
        public virtual ICollection<base_moduleFormAuthorizeAction> base_moduleFormAuthorizeAction { get; set; }
        public virtual ICollection<base_moduleFormActions> base_moduleFormActions { get; set; }
    }
}
